name: Risedle Interface Build
on:
  push:
    branches:
      - preview
      - production
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - preview
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.3.0"
          cache: "npm"
      - run: npm install
      - run: npm run prettier-check
      - run: npm run deploy
