steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: "17.3.0"
          cache: "npm"
    - run: npm install
    - run: npm run prettier
    - run: npm run deploy
